src/main/java/ua/kh/courses/core/db/entity/Course.java
package ua.kh.courses.core.db.entity;

import java.sql.Date;

public class Course extends Entity {

private static final long serialVersionUID = 1L;
	
	private int id;
	private String name;
	private String theme;
	private Date startDate;
	private Date finishDate;
	private int stateId;
	private int countStudent;
	
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Course other = (Course) obj;
		if (id != other.id)
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}
	/**
	 * 
	 */
	public int getId() {
		return id;
	}
	public int getCountStudent() {
		return countStudent;
	}
	public void setCountStudent(int countStudent) {
		this.countStudent = countStudent;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getTheme() {
		return theme;
	}
	public void setTheme(String theme) {
		this.theme = theme;
	}

	public int getState(){
		return stateId;
	}
	
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getFinishDate() {
		return finishDate;
	}
	public void setState(int state_id){
		this.stateId=state_id;
	}
	@Override
	public String toString() {
		return "Course [id=" + id + ", name=" + name + ", theme=" + theme + ", theacher_id="
				+ ", startDate=" + startDate + ", finishDate=" + finishDate + ", state_id=" + stateId
				+ ", countStudent=" + countStudent + "]";
	}
	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

}

src/main/webapp/pages/about_teacher.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<title>Teachers</title>
<link rel="stylesheet" type="text/css" href="styles/reset.css" />
<link rel="stylesheet" type="text/css" href="styles/styles.css" />

</head>
<body>

	<div class="wrapper" align="center">
		<%@ include file="/WEB-INF/jspf/header.jspf"%>

		<div class="context">
			
	
			<%@ include file="/WEB-INF/jspf/navigation.jspf"%>
					<div class="teachers_list_all">
					<table class="teachers_page">
					<tr>	<td><fmt:message key="name"/> </td><td><fmt:message key="last_name"/> </td><td>Email </td><td><fmt:message key="navigation_jspf.courses"/></tr>
					
					
			<c:forEach items="${teachers_list }" var="item">
			<tr><td>${item.fname }</td><td>${item.lname }</td><td>${item.email}</td><td><a class="link_courses" href="controller?command=about_courses&id=${item.id }"><fmt:message key="navigation_jspf.courses"/></a></td></tr>
			</c:forEach>
			</table>
</div>
		</div>



		<%@ include file="/WEB-INF/jspf/footer.jspf"%>
	</div>
</body>
</html>

src/main/webapp/pages/contacts.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<title>Main page</title>
<link rel="stylesheet" type="text/css" href="styles/reset.css" />
<link rel="stylesheet" type="text/css" href="styles/styles.css" />


</head>
<body>

<div class="wrapper" align="center">
<%@ include file="/WEB-INF/jspf/header.jspf"%>

<div class="context">
<%@ include file="/WEB-INF/jspf/navigation.jspf"%>
<div class="teachers_list_all">
	<div class="contact_info">
		<h1 style="margin-bottom: 20px;">`Best IT` - Компания, которая даёт необходимые знания для старта в iT-сфере!</h1>
		<p>Итак, если вы готовы окунуться в мир программирования, тогда вы по адресу!</p>
		<br></br>
		<p>Наши контакты в Харькове:</p>
		<div class="line"></div>
		<h1>Адрес:</h1>	г. Харьков пр. Науки, 20
		<div class="line"></div>
		<h1>Телефоны</h1> +380507907915, +380632958440	
			<div class="line"></div>
			<h1>Email</h1>Best_IT@gmail.com
			</div>
</div>
		</div>




<%@ include file="/WEB-INF/jspf/footer.jspf"%>
</div>
</body>
</html>

src/main/webapp/pages/courses.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<title>Main page</title>
<link rel="stylesheet" type="text/css" href="styles/reset.css" />
<link rel="stylesheet" type="text/css" href="styles/styles.css" />

</head>
<body>

	<div class="wrapper" align="center">
		<%@ include file="/WEB-INF/jspf/header.jspf"%>

		<div class="context">
			<%@ include file="/WEB-INF/jspf/navigation.jspf"%>
			<c:if test="${empty course_list}">
				<p id="course_empty">List of courses are empty!</p>
			</c:if>
			<c:if test="${not empty course_list}">
				<div class="course_list">
<ul id="unit">

					<c:forEach items="${course_list}" var="item">

						<c:if test="${not empty user&& user.roleid==2}">
						
							<li>
								


									<h1>${item.course_name}</h1>
									<p>		<span><fmt:message key="course_name"/>: </span>${item.course_theme}</p>
										<p>	<span><fmt:message key="teacher"/>: </span>${item.teacherFirstName}
											${item.teacherLastName}</p>
									<p>		<span><fmt:message key="number_of_students"/>: </span>${item.studentCount}</p>
										<p>	<span><fmt:message key="course_start_date"/>: </span>${item.startCourse}</p>
										<p>	<span><fmt:message key="course_finish_date"/>: </span>${item.finishCourse}</p>
											<p>	<span><fmt:message key="course_duration"/>: </span>${item.duration} days</p>
										<p>	<span><fmt:message key="status_name"/>: </span>${item.state}</p>
									
										<c:if test="${item.state=='RECRUITED'}">
										<c:if test="${item.signed==true }"><input id="signed_button" type="button" disabled="disabled" value="<fmt:message key="Signed_button"/>"/></c:if>
										<c:if test="${item.signed==false }">
										<form action="controller?command=sign_course&id=${item.id}" method="post">
										<input class="manage_button" style="height:25px; font: 14px sans-serif; " type="submit" value="Подписаться">
										</form>
										</c:if>
										
									
										
										</c:if>
									
								
							</li>
						
						</c:if>
						<c:if test="${not empty user&& user.roleid==1}">
						
							<li>
								
									
									<h1>${item.course_name}</h1>
									<p>		<span><fmt:message key="course_theme"/>: </span>${item.course_theme}</p>
										<p>	<span><fmt:message key="teacher"/>: </span>${item.teacherFirstName}
											${item.teacherLastName}</p>
									<p>		<span><fmt:message key="number_of_students"/>: </span>${item.studentCount}</p>
										<p>	<span><fmt:message key="course_start_date"/>: </span>${item.startCourse}</p>
										<p>	<span><fmt:message key="course_finish_date"/>: </span>${item.finishCourse}</p>
											<p><span><fmt:message key="course_duration"/>: </span>${item.duration} days</p>
										<p>	<span><fmt:message key="status_name"/>: </span>${item.state}</p>
										
										
									
								
							</li>
						
						</c:if>
						<c:if test="${not empty user&& user.roleid==0||user.roleid==3}">
						
							<li>
								
									
								
										<h1>${item.course_name}</h1>
									<p>		<span><fmt:message key="course_theme"/>: </span>${item.course_theme}</p>
										<p>	<span><fmt:message key="teacher"/>: </span>${item.teacherFirstName}
											${item.teacherLastName}</p>
									<p>		<span><fmt:message key="number_of_students"/>: </span>${item.studentCount}</p>
										<p>	<span><fmt:message key="course_start_date"/>: </span>${item.startCourse}</p>
										<p>	<span><fmt:message key="course_finish_date"/>: </span>${item.finishCourse}</p>
											<p><span><fmt:message key="course_duration"/>: </span>${item.duration} days</p>
										<p>	<span><fmt:message key="status_name"/>: </span>${item.state}</p>
								
							</li>
						
						</c:if>
							<c:if test="${ empty user}">
						
							<li>
								





									<h1>${item.course_name}</h1>
									<p>		<span><fmt:message key="course_theme"/>: </span>${item.course_theme}</p>
										<p>	<span><fmt:message key="teacher"/>: </span>${item.teacherFirstName}
											${item.teacherLastName}</p>
									<p>		<span><fmt:message key="number_of_students"/>: </span>${item.studentCount}</p>
										<p>	<span><fmt:message key="course_start_date"/>: </span>${item.startCourse}</p>
										<p>	<span><fmt:message key="course_finish_date"/>: </span>${item.finishCourse}</p>
											<p>	<span><fmt:message key="course_duration"/>: </span>${item.duration} days</p>
										<p>	<span><fmt:message key="status_name"/>: </span>${item.state}</p>
										<c:if test="${item.state=='RECRUITED'}">
										<p style="color: red">Please, sign to registration!</p>
										</c:if>
										
									
								
							</li>
						
						</c:if>
						
					</c:forEach>
</ul>
				</div>
			
			<div>
				<div class="sorting">
					<ul>

						<li><a id="select-sort"><fmt:message key="sorting_button"/></a>
							<ul id="sorting-list">
							<li><a href="controller?command=about_courses">	<fmt:message key="sorting_none"/></a></li>
								<li><a href="controller?command=about_courses&sort=nameA"><fmt:message key="sorting_by_name_a_z"/></a></li>
								<li><a href="controller?command=about_courses&sort=nameZ"><fmt:message key="sorting_by_name_z_a"/></a></li>
								<li><a href="controller?command=about_courses&sort=count"><fmt:message key="sorting_by_student_count"/></a></li>
								<li><a href="controller?command=about_courses&sort=duration"><fmt:message key="sorting_by_long"/></a></li>
							




							</ul></li>
							<li style="padding-top: 5px;"><a id="select-theme"><fmt:message key="course_theme"/></a>
							<ul id="theme_list">
							
								<c:forEach items="${theme}" var="item">
								<li><a href="controller?command=about_courses&theme=${item}">${item}</a></li>
								
								</c:forEach>



							</ul></li>
							<li style="padding-top: 5px;"><a id="select-teacher"><fmt:message key="teacher"/></a>
							<ul id="teacher_list_choise">
							
							<c:forEach items="${teacher_list }" var="item">
							<li><a href="controller?command=about_courses&id=${item.id }">${item.fname } ${item.lname }</a></li>
					
							</c:forEach>
							
							




							</ul></li>
					</ul>
				</div>
			
					<ul>

						
					</ul>
				</div>
				
				
				
				
			</c:if>

		</div>



		<%@ include file="/WEB-INF/jspf/footer.jspf"%>
	</div>
</body>
</html>

src/main/webapp/pages/error_page.jsp
<%@ page isErrorPage="true" %>
<%@ page import="java.io.PrintWriter" %>
   <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>



	
<body>

	<table id="main-container">


		<tr >
			<td class="content">
			<%-- CONTENT --%>
				
				<h2 class="error">
					The following error occurred
				</h2>
			
				<%-- this way we obtain an information about an exception (if it has been occurred) --%>
				<c:set var="code" value="${requestScope['javax.servlet.error.status_code']}"/>
				<c:set var="message" value="${requestScope['javax.servlet.error.message']}"/>
				<c:set var="exception" value="${requestScope['javax.servlet.error.exception']}"/>
				
				<c:if test="${not empty code}">
					<h3>Error code: ${code}</h3>
				</c:if>			
				
				<c:if test="${not empty message}">
					<h3>${message}</h3>
				</c:if>
				
				<c:if test="${not empty exception}">
					<% exception.printStackTrace(new PrintWriter(out)); %>
				</c:if>
				
				<%-- if we get this page using forward --%>
				<c:if test="${not empty requestScope.errorMessage}">
					<h3>${requestScope.errorMessage}</h3>
				</c:if>

			<%-- CONTENT --%>
			</td>
		</tr>

		
	</table>
</body>
</html>

src/main/webapp/pages/forget.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<title>Main page</title>
<link rel="stylesheet" type="text/css" href="styles/reset.css" />
<link rel="stylesheet" type="text/css" href="styles/styles.css" />

</head>
<body>
	<div class="wrapper" align="center">
		<%@ include file="/WEB-INF/jspf/header.jspf"%>

		<div class="context">
			<%@ include file="/WEB-INF/jspf/navigation.jspf"%>

<c:out value="${OK}"></c:out>
			<div class="forget_block">
				<h1>Востановление пароля</h1>
				<form action="controller?command=forget_password" id="forget_form" method="post">
					<table id="autenth_table">
						
						<tr>
							<td>Email</td>
							<td><span>*</span></td>
							<td><input type="text" name="email" /></td>
						</tr>
					</table>
					<input type="submit" value="<fmt:message key="send"/>" id="forget_button">
				</form>
			</div>
		</div>
<%@ include file="/WEB-INF/jspf/footer.jspf"%>
	</div>

</body>
</html>

src/main/webapp/pages/registration.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<title>Main page</title>
<link rel="stylesheet" type="text/css" href="styles/reset.css" />
<link rel="stylesheet" type="text/css" href="styles/styles.css" />




</head>
<body>
	<div class="wrapper" align="center">
		<%@ include file="/WEB-INF/jspf/header.jspf"%>

		<div class="context">
			<%@ include file="/WEB-INF/jspf/navigation.jspf"%>

<c:out value="${OK}"></c:out>
			<div class="registration_block">
				<h1>Registration</h1>
				<form action="controller?command=registration_student" id="registration_form" method="post">
					<table id="autenth_table">
						<tr>
							<td><fmt:message key="name"/></td>
							<td><span>*</span></td>
							<td><input type="text" name="fname" /></td>
						</tr>
						<tr>
							<td><fmt:message key="last_name"/></td>
							<td><span>*</span></td>
							<td><input type="text" name="lname" /></td>
							
						</tr>
						<tr>
							<td><fmt:message key="login"/></td>
							<td><span>*</span></td>
							<td><input type="text" name="login" /></td>
						</tr>
						<tr>
							<td><fmt:message key="password"/></td>
							<td><span>*</span></td>
							<td><input type="text" name="password" id="password" /></td>
						</tr>
						<tr>
							<td><fmt:message key="confirm"/></td>
							<td><span>*</span></td>
							<td><input type="text" name="cpassword" /></td>
						</tr>
						<tr>
							<td>Email</td>
							<td><span>*</span></td>
							<td><input type="text" name="email" /></td>
						</tr>
					</table>
					<input type="submit" value="<fmt:message key="send"/>" id="reg_button">
				</form>




			</div>
		</div>
<%@ include file="/WEB-INF/jspf/footer.jspf"%>
	</div>

	

</body>
</html>

src/main/webapp/pages/search.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<title>Main page</title>
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/styles/reset.css" />
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/styles/styles.css" />

</head>
<body>

	<div class="wrapper" align="center">
		<%@ include file="/WEB-INF/jspf/header.jspf"%>

		<div class="context">
			<%@ include file="/WEB-INF/jspf/navigation.jspf"%>
			<c:if test="${empty course_list}">
				<p id="course_empty">List of courses are empty!</p>
				${search }
			</c:if>
			<c:if test="${not empty course_list}">
				<div class="course_list">
<ul id="unit">

					<c:forEach items="${course_list}" var="item">

						<c:if test="${not empty user&& user.roleid==2}">
						
							<li>
								


									<h1>${item.course_name}</h1>
									<p>		<span><fmt:message key="course_name"/>: </span>${item.course_theme}</p>
										<p>	<span><fmt:message key="teacher"/>: </span>${item.teacherFirstName}
											${item.teacherLastName}</p>
									<p>		<span><fmt:message key="number_of_students"/>: </span>${item.studentCount}</p>
										<p>	<span><fmt:message key="course_start_date"/>: </span>${item.startCourse}</p>
										<p>	<span><fmt:message key="course_finish_date"/>: </span>${item.finishCourse}</p>
											<p>	<span><fmt:message key="course_duration"/>: </span>${item.duration} days</p>
										<p>	<span><fmt:message key="status_name"/>: </span>${item.state}</p>
									
										<c:if test="${item.state=='RECRUITED'}">
										<c:if test="${item.signed==true }"><input id="signed_button" type="button" disabled="disabled" value="<fmt:message key="Signed_button"/>"/></c:if>
										<c:if test="${item.signed==false }">
										<form action="controller?command=sign_course&id=${item.id}" method="post">
										<input class="manage_button" type="submit" value="Подписаться">
										</form>
										</c:if>
										
									
										
										</c:if>
									
								
							</li>
						
						</c:if>
						<c:if test="${not empty user&& user.roleid==1}">
						
							<li>
								
									
									<h1>${item.course_name}</h1>
									<p>		<span><fmt:message key="course_theme"/>: </span>${item.course_theme}</p>
										<p>	<span><fmt:message key="teacher"/>: </span>${item.teacherFirstName}
											${item.teacherLastName}</p>
									<p>		<span><fmt:message key="number_of_students"/>: </span>${item.studentCount}</p>
										<p>	<span><fmt:message key="course_start_date"/>: </span>${item.startCourse}</p>
										<p>	<span><fmt:message key="course_finish_date"/>: </span>${item.finishCourse}</p>
											<p><span><fmt:message key="course_duration"/>: </span>${item.duration} days</p>
										<p>	<span><fmt:message key="status_name"/>: </span>${item.state}</p>
										
										
									
								
							</li>
						
						</c:if>
						<c:if test="${not empty user&& user.roleid==0}">
						
							<li>
								
									
								
										<h1>${item.course_name}</h1>
									<p>		<span><fmt:message key="course_theme"/>: </span>${item.course_theme}</p>
										<p>	<span><fmt:message key="teacher"/>: </span>${item.teacherFirstName}
											${item.teacherLastName}</p>
									<p>		<span><fmt:message key="number_of_students"/>: </span>${item.studentCount}</p>
										<p>	<span><fmt:message key="course_start_date"/>: </span>${item.startCourse}</p>
										<p>	<span><fmt:message key="course_finish_date"/>: </span>${item.finishCourse}</p>
											<p><span><fmt:message key="course_duration"/>: </span>${item.duration} days</p>
										<p>	<span><fmt:message key="status_name"/>: </span>${item.state}</p>
								
							</li>
						
						</c:if>
							<c:if test="${ empty user}">
						
							<li>
								





									<h1>${item.course_name}</h1>
									<p>		<span><fmt:message key="course_theme"/>: </span>${item.course_theme}</p>
										<p>	<span><fmt:message key="teacher"/>: </span>${item.teacherFirstName}
											${item.teacherLastName}</p>
									<p>		<span><fmt:message key="number_of_students"/>: </span>${item.studentCount}</p>
										<p>	<span><fmt:message key="course_start_date"/>: </span>${item.startCourse}</p>
										<p>	<span><fmt:message key="course_finish_date"/>: </span>${item.finishCourse}</p>
											<p>	<span><fmt:message key="course_duration"/>: </span>${item.duration} days</p>
										<p>	<span><fmt:message key="status_name"/>: </span>${item.state}</p>
										<c:if test="${item.state=='RECRUITED'}">
										<p style="color: red">Please, sign to registration!</p>
										</c:if>
										
									
								
							</li>
						
						</c:if>
						
					</c:forEach>
</ul>
				</div>
			
			<div>
				
			
					<ul>

						
					</ul>
				</div>
				
				
				
				
			</c:if>

		</div>



		<%@ include file="/WEB-INF/jspf/footer.jspf"%>
	</div>
</body>
</html>